config/routes.rb
Rails.application.routes.draw do
  


  resources :attachments, only: [:create,:destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create,:destroy]
  devise_for :users

  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"

  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id",as: :add_to_cart,to: "in_shopping_carts#create"
  get "/checkout", to: "payments#checkout" 
  get "/descargar/:id", to:"links#download"
  get "/descargar/:id/archivo/:attachment_id", to:"links#download_attachment",as: :download_attachment
  get "/invalid", to: "welcome#unregistered"
  get "/ok", to: "welcome#payment_succed"



  authenticated :user do
  	root 'welcome#index'
  end

  unauthenticated :user do
  	devise_scope :user do
  		root 'welcome#unregistered', as: :unregistered_root
  	end
  end


end

app/views/partials/_nav.haml
%header
	%nav.black
		%ul.no-list.no-padding.text-center
			%li.col-md-4.inline-block
				-if user_signed_in?
					=link_to root_path, class:"right-space white-text" do
						%i.mdi-action-shopping-basket
						Tienda Online
					=link_to root_path, class:"right-space white-text" do
						%i.mdi-action-trending-up
						Compras
					=link_to root_path, class:"right-space white-text" do
						%i.mdi-action-alarm
						Ofertas-Descuentos
					
			%li.col-md-4.inline-block.text-center
				=image_tag "valknut.svg", height:"100px"
			%li.col-md-4.inline-block
				=link_to carrito_path,class:"white-text right-space" do
					%i.mdi-action-shopping-cart
					Mi Carro
					(
					= @shopping_cart.products.count
					)
				=link_to "Cerrar sesion",destroy_user_session_path,method: :delete , class:"white-text "