config/routes.rb
Rails.application.routes.draw do
  


  resources :attachments, only: [:create,:destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create,:destroy]
  devise_for :users

  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"

  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id",as: :add_to_cart,to: "in_shopping_carts#create"
  get "/checkout", to: "payments#checkout" 
  get "/descargar/:id", to:"links#download"
  get "/descargar/:id/archivo/:attachment_id", to:"links#download_attachment",as: :download_attachment
  get "/invalid", to: "welcome#unregistered"
  get "/ok", to: "welcome#payment_succed"



  authenticated :user do
  	root 'welcome#index'
  end

  unauthenticated :user do
  	devise_scope :user do
  		root 'welcome#unregistered', as: :unregistered_root
  	end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
#  layout 'landing'
  def index
    @orders = current_user.orders.order("created_at desc")
  end

  def unregistered
 	render layout:"landing"
  end

  def payment_succed
  	if @shopping_cart.payed?
  		cookies[:shopping_cart_id] = nil
  	else
  		redirect_to carrito_path
  	end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.haml
.col-xs-11.col-md-10.center-block.no-float
	.card.large-padding
		.top-space
			.col-md-3.col-xs-12.inline-block.no-padding.in-top
				=render current_user.products
			.col-md-9.col-xs-12.inline-block
				=render "payments/index"

app/views/welcome/payment_succed.haml
.col-md-10.center-block.no-float
	%article.card.large-padding
		%h1 El pago ha sido procesado
		%p Los accesos a la descarga han sido enviados al correo proporcionado
		%h2 Resumen de compra
		%table.table.table-striped.table-hover.medium#table_shopping_cart
			%thead
				%td Producto
				%td Precio
			%tbody
				-@shopping_cart.in_shopping_carts.each do |i_sh|
					-product = i_sh.product
					%tr{id: "#{product.id}"}
						%td= product.name
						%td= product.pricing
						

app/views/welcome/unregistered.haml
%header.black.big-padding
	.col-md-10.no-float.center-block
		.col-md-6.no-padding.inline-block
			=image_tag "valknut.svg",width:"100"
			%h1.white-text.ultra-big.scrat
				
				Levantate y Pelea
		.col-md-5.inline-block
			=image_tag "crow.png"
.blue.white-text.big-padding.scrat
	%h2.bigger.scrat.text-center

		publica con nosotros
	%div.text-center
		.col-md-3.inline-block.text-left
			=image_tag "upload-icon.png", class:"col-md-8 inline-block"
			.top-space
				%span.medium.octin
					sube tu producto en linea
				%p.white-text.text-justify.small.octin
					Carga tu producto el cual quieras
					promocionar y listo.
		.col-md-3.inline-block.text-left
			=image_tag "promo.png", class:"col-md-8 inline-block"
			.top-space
				%span.medium.octin
					promocionalo en tus redes
				%p.white-text.text-justify.small.octin
					envia el link para que tu producto sea visto
		.col-md-3.inline-block.text-left
			=image_tag "payment.png", class:"col-md-8 inline-block"
			.top-space
				%span.medium.octin
					vende online
				%p.white-text.text-justify.small.octin
					vende en linea y de forma rapida y segura
.white.text-center.big-padding.octin{style:"margin-top:5em;"}
	.col-md-3.inline-block.text-left
		=image_tag "multimedia.png"
	.col-md-3.inline-block.text-left
		=image_tag "productos.png",width:"250"
		%p.medium.col-md-11.center-block.no-float.top-space
			%strong
				Sube contenido,diseños,productos,publicalos y vende
.top-space.big.padding.white.bottom-space
	.col-md-11.col-xs-12.center-block.no-float
		=form_tag(create_email_path,method: :post,remote:true,id: "emails-form") do
			=email_field_tag "email",nil,class:"col-xs-12 inline-block text-center landing-form",placeholder:"Subscribe  tu correo aqui (Subscribe here)"
		#email-info.blue.white-text.large-padding